services:
  devcontainer:
    build: .
    volumes:
      - ./../:/workspaces/go-scratchpad
      # Forward docker socket to allow docker commands to be run from within the container
      - /var/run/docker.sock:/var/run/docker.sock
      - devcontainer-zshhistory:/root/commandhistory/.zsh_history
    command: sleep infinity
  db:
    image: 'postgres'
    restart: 'always'
    environment:
      POSTGRES_USER: 'username'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'testdb'
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
volumes:
  devcontainer-zshhistory:
